version: '3'

services:
  db:
    image: mysql:latest
    volumes: 
      - ./mysql-init-files/:/docker-entrypoint-initdb.d/
      - ./mysql-config-files/:/etc/mysql/conf.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=oauth2_test
    depends_on:
      - db-master
    ports:
      - 3306:3306
    expose:
      - 3306
  redis:
    image: redis:latest
    ports: 
      - 6379:6379
    expose:
      - 6379